### ISSUE TITLE
Error ERR_HTTP_HEADERS_SENT on POST to dialog/authorize/decision

### ISSUE THREAD

**Issue by theTestTube** [jacobgoh101/nestjs-oauth2orize#2]
Dear Jacob,

Thanks for your minimalistic NestJS approach to the very common OAuth2 auth code grant!

I've found an error that prevents deploying your code to a NodeJS 12.14 AWS Lambda function.

When doing a `POST` to `dialog/authorize/decision`,

``` http
###
# @name GetDialogAuthorize
POST http://localhost:3001/dialog/authorize/decision HTTP/1.1
content-type: application/x-www-form-urlencoded

transaction_id={{transaction}}
```

the following exception denotes that the expected flow of the Express request has been broken,

```
[Nest] 23568   - 2020-1-30 18:31:14   [NestApplication] Nest application successfully started +2ms
(node:23568) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (.\workspace\nestjs-oauth2orize\node_modules\express\lib\response.js:767:10)
    at ServerResponse.send (.\workspace\nestjs-oauth2orize\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (.\workspace\nestjs-oauth2orize\node_modules\express\lib\response.js:267:15)
    at ExpressAdapter.reply (.\workspace\nestjs-oauth2orize\node_modules\@nestjs\core\adapters\express-adapter.js:44:52)
    at ExceptionsHandler.catch (.\workspace\nestjs-oauth2orize\node_modules\@nestjs\core\exceptions\base-exception-filter.js:41:24)     
    at ExceptionsHandler.next (.\workspace\nestjs-oauth2orize\node_modules\@nestjs\core\exceptions\exceptions-handler.js:15:20)        
    at .\workspace\nestjs-oauth2orize\node_modules\@nestjs\core\router\router-proxy.js:23:35
    at Layer.handle_error (.\workspace\nestjs-oauth2orize\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (.\workspace\nestjs-oauth2orize\node_modules\express\lib\router\index.js:315:13)
(node:23568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a cattch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate  the Node.js process with a non-zero exit code.
```

When running locally with the `@nestjs/platform-express` adapter, server error occurs but HTTP client doesn't perceive any error. An HTTP 302 status is received with the right location for the `dialog/authorize?redirect_uri=...` specified.

When proxying to a Lambda function with an `aws-serverless-express` server the  `UnhandledPromiseRejectionWarning` is anormally ending the request and an HTTP 502 is received by the client.

Regards.-

**Comment by Meera24** [comment]
Hi.... The code said grant type not supported. Can I know the reason?
